version: 1
disable_existing_loggers: False

formatters:
  standard:
    format: "%(asctime)s [%(levelname)s] %(name)s: %(message)s"

handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: standart
    stream: ext://sys.stdout

  file:
    class: logging.handlers.RotatingFileHandler
    level: ERROR
    formatter: standart
    filename: "logs/errors.log"
    mode: "a"
    maxBytes: 5242880
    backupCount: 5

loggers:
  app.routers:
    level: DEBUG
    handlers: [console, file]
    propagate: False

root:
  level: INFO
  handlers: [console, file]