"""Add clicks column

Revision ID: b5201a6c6c70
Revises: 6920f9048c43
Create Date: 2026-05-02 16:12:56.339610

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5201a6c6c70'
down_revision: Union[str, Sequence[str], None] = '6920f9048c43'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('links', sa.Column('clicks', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('links', 'clicks')
    # ### end Alembic commands ###
