"""Table Logos was rename

Revision ID: cc7a10ecd000
Revises: 8244b3e94e96
Create Date: 2026-05-04 20:24:35.937953

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cc7a10ecd000'
down_revision: Union[str, Sequence[str], None] = '8244b3e94e96'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('logos',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('bytes_image', sa.LargeBinary(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.drop_table('Logos')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Logos',
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('bytes_image', postgresql.BYTEA(), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('Logos_pkey')),
    sa.UniqueConstraint('name', name=op.f('Logos_name_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.drop_table('logos')
    # ### end Alembic commands ###
